//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing.BLL.Resouces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessRulesMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessRulesMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ticketing.BLL.Resouces.BusinessRulesMessages", typeof(BusinessRulesMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This airline can have a maximum of 150 planes.Count Of Planes For This AirLine :{0}.
        /// </summary>
        internal static string airlinecanhavemaximumof150planes {
            get {
                return ResourceManager.GetString("airlinecanhavemaximumof150planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Airplaen Or Airline Does Not Exist!.
        /// </summary>
        internal static string AirplaenAirlineNotExist {
            get {
                return ResourceManager.GetString("AirplaenAirlineNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Airworthiness Does Not Update!.
        /// </summary>
        internal static string AirworthinessDoesNotUpdate {
            get {
                return ResourceManager.GetString("AirworthinessDoesNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        internal static string America {
            get {
                return ResourceManager.GetString("America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American airlines only have Boeing airplanes.
        /// </summary>
        internal static string AmericanairlinesonlyhaveBoeing {
            get {
                return ResourceManager.GetString("AmericanairlinesonlyhaveBoeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to american airlines and Qatar Airways can have a maximum of 200 planes.Count Of Planes For This Airline : {0}.
        /// </summary>
        internal static string AmericanAndQatarAirwaysHaveMaximum200lanes {
            get {
                return ResourceManager.GetString("AmericanAndQatarAirwaysHaveMaximum200lanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Does Not Exist!.
        /// </summary>
        internal static string CompanyDoesNotExist {
            get {
                return ResourceManager.GetString("CompanyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password=12345;Persist Security Info=True;User ID=sa;Initial Catalog=LoginPage;Data Source=.;TrustServerCertificate=Yes.
        /// </summary>
        internal static string ConectionString {
            get {
                return ResourceManager.GetString("ConectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Does Not Exist!.
        /// </summary>
        internal static string CountryDoesNotExist {
            get {
                return ResourceManager.GetString("CountryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only European airlines and Japanese airlines can have Boeing airplanes.
        /// </summary>
        internal static string EroupeanJapaneseHaveBoeing {
            get {
                return ResourceManager.GetString("EroupeanJapaneseHaveBoeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        internal static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Information Is Required.
        /// </summary>
        internal static string HomeInformationIsRequired {
            get {
                return ResourceManager.GetString("HomeInformationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password Format Is Incorrect.
        /// </summary>
        internal static string IncorectPassword {
            get {
                return ResourceManager.GetString("IncorectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Format Is Incorrect.
        /// </summary>
        internal static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write The Address between 20 and 50 Characters.
        /// </summary>
        internal static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Of Birthday.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location Type Is Invalid.
        /// </summary>
        internal static string InvalidLocation {
            get {
                return ResourceManager.GetString("InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PostalCode.
        /// </summary>
        internal static string InvalidPostalCode {
            get {
                return ResourceManager.GetString("InvalidPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This RegistrationNumber Is Already Exists..
        /// </summary>
        internal static string IsAlreadyExists {
            get {
                return ResourceManager.GetString("IsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It Should Be Less than 5 charactor.
        /// </summary>
        internal static string Lessthan5char {
            get {
                return ResourceManager.GetString("Lessthan5char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Company For This ModelID.
        /// </summary>
        internal static string NoCompanyForThisModelId {
            get {
                return ResourceManager.GetString("NoCompanyForThisModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Continent For This ID.
        /// </summary>
        internal static string NoContinentForThisId {
            get {
                return ResourceManager.GetString("NoContinentForThisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber Is Invalid.Try In This Format : 02144444444.
        /// </summary>
        internal static string PhoneNumberIsInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This RegistrationNumber Is Not With Correct Format.
        /// </summary>
        internal static string RegistrationNumberNotCorrect {
            get {
                return ResourceManager.GetString("RegistrationNumberNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Add More Than 2 Information For This User.
        /// </summary>
        internal static string UnableToAddMoreThan2Information {
            get {
                return ResourceManager.GetString("UnableToAddMoreThan2Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This UserID Does Not Exist In Users.
        /// </summary>
        internal static string UserIDDoesNotExist {
            get {
                return ResourceManager.GetString("UserIDDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Username Is Already Exists. Please Try Another One.
        /// </summary>
        internal static string UsernameIsExist {
            get {
                return ResourceManager.GetString("UsernameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserName Must Be More Than 5 Characters.
        /// </summary>
        internal static string UsernameMustBeMorethan5 {
            get {
                return ResourceManager.GetString("UsernameMustBeMorethan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This UserName Does Not Exist.
        /// </summary>
        internal static string UserNameNotExist {
            get {
                return ResourceManager.GetString("UserNameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Can Not Have More Than 1 Home Address.
        /// </summary>
        internal static string UsersCanNotHaveMoreThan1HomeAddress {
            get {
                return ResourceManager.GetString("UsersCanNotHaveMoreThan1HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongGender.
        /// </summary>
        internal static string WrongGender {
            get {
                return ResourceManager.GetString("WrongGender", resourceCulture);
            }
        }
    }
}
